version: "3"

services:
  # MongoDB services
  mongo:
    container_name: mongo
    image: mongo:latest #should we specify a specific version ?
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - graphql-express

  # Node services
  node_api:
    container_name: api_gambling #optional
    build:
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - graphql-express

volumes:
  mongo: {}

networks:
  graphql-express:

